name = "meu-cloudflare-worker"  
type = "javascript"  
account_id = "seu_account_id"  
workers_dev = true  
route = "https://seu-site.com/*"  
zone_id = "seu_zone_id"  

[build]  
command = ""  
[build.upload]  
format = "service-worker"  